### PR TITLE
fix: remove python version upper bound

### PR DESCRIPTION
**Pull request by JacobHayes**
Capping to <3.11 prevents projects from using (or testing) this package on 3.11 (which I'd like to do for internal projects), so unless there is a known breaking issue in 3.11, this removes the pin. There may be some conflicting opinions, but [this post](https://iscinumpy.dev/post/bound-version-constraints/#tldr) lays out a couple challenges with _libraries_ pinning upper bound. Notably, neither [pandas](https://github.com/pandas-dev/pandas/blob/edf0fce742bf9443e38c035deffa10f6a18591bd/setup.cfg#L38) nor [pyarrow](https://github.com/apache/arrow/blob/93b63e8f3b4880927ccbd5522c967df79e926cda/python/setup.py#L754) set a python upper bound.

--

I'm just making the PR real quick since it is a small change, but happy to close if there are concerns (or open an issue if it needs further discussion).

- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-db-dtypes-pandas/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by chalmerlowe** [comment]
@JacobHayes thanks for submitting this PR. I am checking with some colleagues to see whether there was a particular reason to take this approach. More to come.

**Review by chalmerlowe — APPROVED** [review]
LGTM

**Comment by JacobHayes** [comment]
I think the two failing tests are flakes but not sure about "OwlBot Post Processor".

**Comment by chalmerlowe** [comment]
there is a bug in the pandas release candidate code that handles time down to the nanosecond and it is causing some tests to fail.
They know about about it and last I checked, it was in the works as part of the milestone release. Not super worried about the tests. Will check on what might be the problem with owlbot and see about getting this merged.

**Pull request merged**
